"""Multi-factor signal model — weighted signal scoring with confirmation gate.

Replaces the simple category-based signal generator with a multi-factor model:
  signal_score = w_news * news + w_market * market + w_narrative * narrative + w_novelty * novelty

A signal only fires if at least 2 of 3 factors (news, market, narrative) align.
"""

import json
import logging
from dataclasses import dataclass, field
from typing import Any, Optional

from src.analysis.market_confirmation import MarketConfirmation, MarketContext
from src.analysis.narrative_tracker import NarrativeTracker
from src.analysis.signal_generator import SIGNAL_RULES
from src.processing.source_credibility import SourceCredibility
from src.storage.database import Database

logger = logging.getLogger(__name__)

# Default factor weights
DEFAULT_WEIGHTS = {
    "news": 0.40,
    "market": 0.25,
    "narrative": 0.20,
    "novelty": 0.15,
}

# Confidence thresholds
DEFAULT_THRESHOLDS = {
    "high": 0.7,
    "medium": 0.4,
    "noise": 0.4,  # below this = no signal
}


@dataclass
class MultiFactorSignal:
    """A signal generated by the multi-factor model."""

    cluster_id: int
    asset: str
    direction: str  # 'long', 'short'
    confidence: str  # 'HIGH', 'MEDIUM'
    signal_score: float  # 0-1 composite score

    # Factor components (0-1 each)
    news_component: float
    market_component: float
    narrative_component: float
    novelty_component: float

    # Market context
    entry_time: str
    price_at_signal: float
    volume_zscore: float
    momentum_1h: float

    # Confirmation
    confirmation_factors: list[str]  # which factors aligned
    reasoning: str

    category: str = ""
    severity: int = 0


class MultiFactorSignalGenerator:
    """Generate signals using weighted multi-factor scoring.

    Factors:
    1. News signal: category direction x severity x sentiment x source credibility
    2. Market confirmation: volume z-score x momentum alignment
    3. Narrative strength: event count in narrative x recency x escalation
    4. Novelty score: exponential decay from Phase 6

    Gate: signal fires only if >= 2 of (news, market, narrative) align.
    """

    def __init__(self, db: Database, config: Optional[dict[str, Any]] = None) -> None:
        self.db = db
        self.config = config or {}

        cfg = self.config.get("signal_model", {})
        weights = cfg.get("weights", DEFAULT_WEIGHTS)
        self.w_news = weights.get("news", DEFAULT_WEIGHTS["news"])
        self.w_market = weights.get("market", DEFAULT_WEIGHTS["market"])
        self.w_narrative = weights.get("narrative", DEFAULT_WEIGHTS["narrative"])
        self.w_novelty = weights.get("novelty", DEFAULT_WEIGHTS["novelty"])

        thresholds = cfg.get("thresholds", DEFAULT_THRESHOLDS)
        self.high_threshold = thresholds.get("high", DEFAULT_THRESHOLDS["high"])
        self.medium_threshold = thresholds.get("medium", DEFAULT_THRESHOLDS["medium"])
        self.min_confirmation_factors = cfg.get("min_confirmation_factors", 2)

        self.market = MarketConfirmation(db, config)
        self.credibility = SourceCredibility(config)
        self._narrative_cache: Optional[dict[str, Any]] = None

    def generate_all(self, since: Optional[str] = None) -> list[MultiFactorSignal]:
        """Generate multi-factor signals from event clusters.

        Args:
            since: Only process clusters detected after this timestamp.

        Returns:
            List of MultiFactorSignal objects that pass the confirmation gate.
        """
        clusters = self._get_clusters(since)
        if not clusters:
            logger.info("No clusters to generate signals from")
            return []

        # Pre-compute narrative data
        self._build_narrative_cache()

        all_signals: list[MultiFactorSignal] = []

        for cluster in clusters:
            signals = self._score_cluster(cluster)
            all_signals.extend(signals)

        logger.info(
            "Multi-factor generator: %d signals from %d clusters",
            len(all_signals), len(clusters),
        )
        return all_signals

    def generate_and_store(self, since: Optional[str] = None) -> int:
        """Generate multi-factor signals and persist to database.

        Returns:
            Number of signals stored.
        """
        signals = self.generate_all(since=since)
        stored = 0

        for sig in signals:
            self._store_signal(sig)
            stored += 1

        logger.info("Stored %d multi-factor signals", stored)
        return stored

    def _score_cluster(self, cluster: dict[str, Any]) -> list[MultiFactorSignal]:
        """Score a single event cluster and generate signals for affected assets.

        Args:
            cluster: Event cluster dict.

        Returns:
            List of signals (one per asset) that pass the confirmation gate.
        """
        category = cluster["category"]
        severity = cluster["severity"]
        summary = cluster.get("summary", cluster.get("representative_headline", ""))
        assets = cluster.get("assets_affected", [])
        detected_at = cluster.get("detected_at", cluster.get("first_detected_at", ""))
        novelty = cluster.get("novelty_score", 1.0) or 1.0

        # Determine direction from news rules
        rule = SIGNAL_RULES.get(category)
        if not rule:
            return []

        if severity < rule.get("min_severity", 1):
            return []

        direction = self._determine_direction(rule, summary)
        if direction == "neutral":
            return []

        # News component
        news_score = self._compute_news_score(
            rule, severity, summary, cluster.get("sentiment", 0.0), direction,
        )

        # Novelty component (already 0-1)
        novelty_score = max(0.0, min(1.0, novelty))

        # Narrative component
        narrative_score = self._compute_narrative_score(category, assets)

        signals: list[MultiFactorSignal] = []

        for asset in assets:
            # Market component (asset-specific)
            market_ctx = self.market.get_market_context(asset, detected_at, direction)

            if market_ctx:
                market_score = self.market.compute_confirmation_score(market_ctx)
                volume_zscore = market_ctx.volume_zscore
                momentum_1h = market_ctx.momentum_1h
                price = market_ctx.price
            else:
                market_score = 0.5  # neutral when no market data
                volume_zscore = 0.0
                momentum_1h = 0.0
                price_data = self.db.get_price_at(asset, detected_at)
                price = price_data["close"] if price_data else 0.0

            # Composite score
            signal_score = (
                self.w_news * news_score
                + self.w_market * market_score
                + self.w_narrative * narrative_score
                + self.w_novelty * novelty_score
            )

            # Confirmation gate: count how many of the 3 main factors support
            confirmation_factors = []
            if news_score >= 0.4:
                confirmation_factors.append("news")
            if market_ctx and market_ctx.volume_confirmed and market_ctx.momentum_aligned:
                confirmation_factors.append("market")
            if narrative_score >= 0.3:
                confirmation_factors.append("narrative")

            # Gate: need >= min_confirmation_factors
            if len(confirmation_factors) < self.min_confirmation_factors:
                continue

            # Threshold check
            if signal_score < self.medium_threshold:
                continue

            # Classify confidence
            if signal_score >= self.high_threshold:
                confidence_label = "HIGH"
            else:
                confidence_label = "MEDIUM"

            # Build reasoning
            reasoning = self._build_reasoning(
                category, direction, news_score, market_score,
                narrative_score, novelty_score, confirmation_factors,
                volume_zscore, momentum_1h,
            )

            sig = MultiFactorSignal(
                cluster_id=cluster["id"],
                asset=asset,
                direction=direction,
                confidence=confidence_label,
                signal_score=round(signal_score, 4),
                news_component=round(news_score, 4),
                market_component=round(market_score, 4),
                narrative_component=round(narrative_score, 4),
                novelty_component=round(novelty_score, 4),
                entry_time=detected_at,
                price_at_signal=price,
                volume_zscore=round(volume_zscore, 4),
                momentum_1h=round(momentum_1h, 4),
                confirmation_factors=confirmation_factors,
                reasoning=reasoning,
                category=category,
                severity=severity,
            )
            signals.append(sig)

        return signals

    def _compute_news_score(
        self,
        rule: dict[str, Any],
        severity: int,
        summary: str,
        sentiment: float,
        direction: str,
    ) -> float:
        """Compute news component score.

        news = base_confidence × severity_factor × sentiment_alignment

        Args:
            rule: Signal rule dict for this category.
            severity: Event severity 1-5.
            summary: Event summary text.
            sentiment: Sentiment score (-1 to 1).
            direction: Signal direction.

        Returns:
            Score between 0.0 and 1.0.
        """
        base = rule.get("base_confidence", 0.4)

        # Severity factor: normalize to 0-1 range
        severity_factor = severity / 5.0

        # Sentiment alignment: positive sentiment + long = boost, mismatch = penalize
        if direction == "long":
            sentiment_factor = 0.5 + (sentiment * 0.5)  # maps [-1,1] to [0,1]
        else:
            sentiment_factor = 0.5 - (sentiment * 0.5)  # inverted for short

        score = base * (0.3 + 0.7 * severity_factor) * (0.5 + 0.5 * sentiment_factor)
        return min(1.0, max(0.0, score))

    def _compute_narrative_score(
        self, category: str, assets: list[str]
    ) -> float:
        """Compute narrative component score.

        Higher score when the event is part of an active, escalating narrative.

        Args:
            category: Event category.
            assets: Affected asset symbols.

        Returns:
            Score between 0.0 and 1.0.
        """
        if not self._narrative_cache:
            return 0.0

        best_score = 0.0
        for name, data in self._narrative_cache.items():
            # Check if this narrative overlaps with the event
            if data["event_count"] < 2:
                continue

            # Overlap: does the narrative share assets with this event?
            overlap = bool(set(assets) & set(data.get("top_assets", [])))
            if not overlap:
                continue

            # Score: event_count × momentum × recency
            count_factor = min(1.0, data["event_count"] / 20.0)  # caps at 20
            momentum = data.get("momentum", 0.0)
            score = count_factor * (0.3 + 0.7 * momentum)

            best_score = max(best_score, score)

        return min(1.0, best_score)

    def _build_narrative_cache(self) -> None:
        """Pre-compute narrative data for scoring."""
        try:
            tracker = NarrativeTracker(self.db, self.config)
            snapshots = tracker.update_narratives(days=30)
            self._narrative_cache = {}
            for s in snapshots:
                self._narrative_cache[s.name] = {
                    "event_count": s.event_count,
                    "recent_count": s.recent_count,
                    "momentum": s.momentum,
                    "top_assets": s.top_assets,
                }
        except Exception:
            logger.warning("Could not build narrative cache")
            self._narrative_cache = {}

    def _determine_direction(self, rule: dict[str, Any], text: str) -> str:
        """Determine signal direction from rule keywords."""
        text_lower = text.lower()
        pos_kws = rule.get("positive_keywords", [])
        if any(kw in text_lower for kw in pos_kws):
            return rule.get("positive_direction", "long")
        neg_kws = rule.get("negative_keywords", [])
        if any(kw in text_lower for kw in neg_kws):
            return rule.get("negative_direction", "short")
        return rule.get("default_direction", "neutral")

    def _build_reasoning(
        self,
        category: str,
        direction: str,
        news: float,
        market: float,
        narrative: float,
        novelty: float,
        factors: list[str],
        vol_z: float,
        mom: float,
    ) -> str:
        """Build human-readable reasoning for a signal."""
        parts = [
            f"{category} event -> {direction}",
            f"news={news:.2f}",
            f"market={market:.2f} (vol_z={vol_z:.1f}, mom={mom:+.1f}%)",
            f"narrative={narrative:.2f}",
            f"novelty={novelty:.2f}",
            f"confirmed by: {', '.join(factors)}",
        ]
        return " | ".join(parts)

    def _get_clusters(self, since: Optional[str] = None) -> list[dict[str, Any]]:
        """Get event clusters for signal generation."""
        query = """
            SELECT id, category, severity, sentiment,
                   first_detected_at AS detected_at,
                   assets_affected, representative_headline AS summary,
                   novelty_score, article_count
            FROM event_clusters
            WHERE 1=1
        """
        params: list[Any] = []
        if since:
            query += " AND first_detected_at >= ?"
            params.append(since)
        query += " ORDER BY first_detected_at DESC LIMIT 10000"

        with self.db.connect() as conn:
            rows = conn.execute(query, params).fetchall()
            results = []
            for r in rows:
                d = dict(r)
                d["assets_affected"] = json.loads(d.get("assets_affected", "[]"))
                results.append(d)
            return results

    def _store_signal(self, sig: MultiFactorSignal) -> int:
        """Persist a multi-factor signal to the database.

        Uses the extended signals_v2 table.
        """
        confirmation_json = json.dumps(sig.confirmation_factors)

        with self.db.connect() as conn:
            cursor = conn.execute(
                """INSERT INTO signals_v2
                   (cluster_id, asset, direction, confidence, signal_score,
                    news_component, market_component, narrative_component,
                    novelty_component, entry_time, price_at_signal,
                    volume_zscore, momentum_1h,
                    confirmation_factors, reasoning)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    sig.cluster_id, sig.asset, sig.direction, sig.confidence,
                    sig.signal_score, sig.news_component, sig.market_component,
                    sig.narrative_component, sig.novelty_component,
                    sig.entry_time, sig.price_at_signal,
                    sig.volume_zscore, sig.momentum_1h,
                    confirmation_json, sig.reasoning,
                ),
            )
            conn.commit()
            return cursor.lastrowid
